// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package simbad_simulation;

public class Coordinate {

    private int latitude;
    private int longitude;

    public Coordinate(int lat, int lon) {
        latitude = lat;
        longitude = lon;
    }

    public int getLongitude() {
        return longitude;
    }

    public int getLatitude() {
        return latitude;
    }
};
