// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package simbad_simulation;

public enum ERequest {
    EXPLORE,
    SCAN,
    MEASURE;
};
