// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package simbad_simulation;

public abstract class Observer {

    protected Subject subject;

    public abstract void update();
};
