// -------photos-------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package simbad_simulation;

import java.util.ArrayList;

public class PhotoRover extends Rover {

    private ArrayList<Scan> storage;

    public PhotoRover() {
        super();
        storage = new ArrayList<Scan>();
        System.out.println("Creating a new PhotoRover object");
    }

    public void scanPosition() {
        Photo[] photos = new Photo[4];

        for (int i=0 ; i<4 ; ++i) {
            photos[i].setCoord(getPosition());
            photos[i].setDirection(getOrientation());
            rotate(getOrientation().next());
        }

        storage.add(new Scan(photos));
        System.out.println("Rover ["+getId()+"] scanning "+getPosition());
    }

   public boolean sendData() {
        return true;
    }
 
    public void freeStorage() {
        storage.clear();
        System.out.println("Clearing storage");
    }
};
