// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package simbad_simulation;

public class Scan {

    private Photo[] photos = new Photo[4];

    public Scan(Photo[] p) {
        for (int i=0 ; i<p.length ; ++i) {
            photos[i] = p[i];
        }
    }
};
