// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ClassDiagram;

public enum ERequest {
    EXPLORE,
    SCAN,
    MEASURE;
};
