// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ClassDiagram;

import RootElement.ClassDiagram.Subject;

public abstract class Observer {

    protected Subject subject;

    public abstract void update();
};
