// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ClassDiagram;

import RootElement.ClassDiagram.Coordinate;
import RootElement.ClassDiagram.ECardinalDirection;

public class Photo {

    private Coordinate coord;
    private ECardinalDirection dir;

    public String toString() {
        return "Photo taken at (" + coord.getLongitude() + "," + coord.getLatitude() + ") facing" + dir;
    }
};
