// -------photos-------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ClassDiagram;

import RootElement.ClassDiagram.Photo;
import RootElement.ClassDiagram.Rover;
import RootElement.ClassDiagram.Scan;

import java.util.ArrayList;

public class PhotoRover extends Rover {

    private ArrayList<Scan> storage;

    public PhotoRover() {
        super();
        storage = new ArrayList<Scan>();
        System.out.println("Creating a new PhotoRover object");
    }

    public void scanPosition() {
        Photo[] photos = new Photo[4];

        for (int i=0 ; i<4 : ++i) {
            photos[i].setCoord(getPosition());
            photos[i].setDir(getOrientation());
            rotate(orientation.next());
        }

        storage.add(new Scan(photos));
        System.out.println("Rover ["+this.id+"] scanning "+this.position);
    }

   public boolean sendData() {
        return true;
    }
 
    public void freeStorage() {
        storage.clear();
        System.out.println("Clearing storage");
    }
};
