// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ClassDiagram;

import RootElement.ClassDiagram.Rover;

public class RoverFactory {

	public Rover createRover(String type) {
      if (type.equals("scouting"))
          return new ScoutingRover();
      else if (type.equals("photo"))
          return new PhotoRover();
      else if (type.equals("carbon"))
          return new CarbonRover();
      else throw new IllegalArgumentException("Robot type must be <scouting> <photo> or <carbon>");
  }	

};
