// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ClassDiagram;

import RootElement.ClassDiagram.Coordinate;
import RootElement.ClassDiagram.Rover;

import java.util.ArrayList;

public class ScoutingRover extends Rover {

    private ArrayList<Coordinate> storage;

    public ScoutingRover() {
        super();
        storage = new ArrayList<Coordinate>();
        System.out.println("Creating a new ScoutingRover object");
    }

    public void savePosition() {
        storage.add(getPosition());
        System.out.println("Rover ["+this.id+"] found an obstacle at "+this.position);
    }

    public boolean sendData() {
        return true;
    }

    public void freeStorage() {
        storage.clear();
        System.out.println("Clearing Storage");
    }
};
