// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ClassDiagram;

import RootElement.ClassDiagram.ERequest;
import RootElement.ClassDiagram.Observer;

import java.util.ArrayList;

public abstract class Subject {

    private ArrayList<Observer> observers = new ArrayList<Observer>();
    private ERequest request;

    public ERequest getRequest() {
        return request;
    }

    public void notifyObservers() {
        for (Observer obs : observers)
            obs.update();
    }

    public void attach(Observer obs) {
        observers.add(obs);
    }

    public void detach(Observer obs) {
        observers.remove(obs);
    }

};
