// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rovusystem;

import java.util.ArrayList;
import javax.vecmath.Vector3d;

public class CarbonRover extends Rover {

    private ArrayList<Scan> storage;

    public CarbonRover(Vector3d pos, String name) {
        super(pos, name);
        System.out.println("Creating a new PhotoRover object");
    }

    public void scanPosition() {
        Photo[] photos = new Photo[4];

        for (int i=0 ; i<4 ; ++i) {
            photos[i].setCoord(getPosition());
            photos[i].setDirection(getOrientation());
            rotate(getOrientation().next());
        }

        storage.add(new Scan(photos));
        System.out.println("Rover ["+getId()+"] scanning "+getPosition());
    }

   public boolean sendData() {
        return true;
    }
 
    public void freeStorage() {
        storage.clear();
        System.out.println("Clearing storage");
    }
};
