// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rovusystem;

import java.util.ArrayList;

public class CentralStation extends Subject {

	private final int MIN_COVERAGE = 80;

    private static CentralStation instance = new CentralStation();

    protected boolean isOnline;
    private int mapCoverage;
    private int storage;
    public EEnvironment[][] environment;
    private ArrayList<Coordinate> relevantCoords;

    private CentralStation() {
    	super();
    	isOnline = true;
    	mapCoverage = 0;
    	storage = 0;
    }

    public static CentralStation getInstance() {
        return instance;
    }

    public boolean getStatus() {
        return isOnline;
    }
    
    /** These operations map 1 to 1 with the Class Diagram
     *  but they don't fit in the Simbad simulation. We will alter
     *  our system for the sake of the sim.
     */
    public EEnvironment[][] getMap() {
    	return environment;
    }

    private void computeRelCoords() {
    }

    private Coordinate[] computeRoute(int id) {
        Coordinate[] route = new Coordinate[42]; // 42 is a placeholder
        return route;
    }

    private void checkCoverage() {
        if (mapCoverage >= MIN_COVERAGE) {
            System.out.println("Minimum coverage requirement fulfilled.");
        }
    }
    
};
