// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rovusystem;

public enum ERequest {
    EXPLORE,
    SCAN,
    MEASURE;
};
