// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rovusystem;

public enum ERequest {
    EXPLORE,
    SCAN,
    MEASURE;
	
	private static ERequest[] vals = values();
    public ERequest next() {
        return vals[(this.ordinal()+1) % vals.length];
    }
};
