// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rovusystem;

import javax.vecmath.Vector3d;
import simbad.sim.Agent;

public abstract class Observer extends Agent {

    public Observer(Vector3d pos, String name) {
		super(pos, name);
	}

	protected Subject subject;

    public abstract void update();
};
