// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rovusystem;

import javax.vecmath.Vector3d;

public class RoverFactory {

	/** Simbad Agent class needs a Vector3d position and a String name **/
	public Rover createRover(String type, Vector3d pos, String name) {
      if (type.equals("scouting"))
          return new ScoutingRover(pos, name);
      else if (type.equals("photo"))
          return new PhotoRover(pos, name);
      else if (type.equals("carbon"))
          return new CarbonRover(pos, name);
      else throw new IllegalArgumentException("Robot type must be <scouting> <photo> or <carbon>");
  }	

};
